name: Build and Deploy Vite Frontend to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: vite-frontend
  ACR_NAME: ucr25
  CONTAINER_APP_NAME: unihack-frontend-app
  RESOURCE_GROUP: UniHack

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Create .env File with Secrets
        run: |
          cd frontend
          echo "VITE_API_BLOCKFROST_API_KEY=${{ secrets.VITE_API_BLOCKFROST_API_KEY }}" >> .env
          echo "VITE_API_APP_BACKEND_URL=${{ secrets.VITE_API_APP_BACKEND_URL }}" >> .env
          echo ".env file created successfully."

      - name: Build and Push Docker Image
        run: |
          cd frontend
          IMAGE_TAG=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Deploy New Image to Azure Container App
        run: |
          IMAGE_TAG=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          az containerapp update \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image $IMAGE_TAG
